# Run locally with act:
#
# act pull_request --workflows .github/workflows/test.yaml

name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    env:
      FUSIONAUTH_URL: http://localhost:9011
      FUSIONAUTH_API_KEY: bf69486b-4733-4470-a592-f1bfce7af580
    steps:
      - uses: actions/checkout@v4

      - name: Set up FusionAuth
        working-directory: src/test/docker
        run: docker compose up -d

      - name: Check to see if FusionAuth is loaded
        run: |
          bash ./src/test/docker/poll-for-kickstart-finish.sh

      - name: Run tests
        shell: bash -l {0}
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          echo -e "\nUsing $(python --version) in $(which python)\n"
          pip install -e .
          echo ""
          pip list
          echo ""
          python src/test/python/fusionauth/rest_client_test.py
          python src/test/python/fusionauth/fusionauth_client_test.py
